---
title: "practice at home"
output: html_notebook
---
```{r}
library(readr)
TyphoonData <- read_csv("https://raw.githubusercontent.com/GaryLKL/course-programming-for-ds-Quiz/master/TyphoonData.csv")
```

```{r}
as.factor(TyphoonData$近臺強度) -> a
as.numeric(TyphoonData$`最低氣壓(hPa)`) -> b
as.numeric(TyphoonData$`最大風速(m/s)`) -> c
as.numeric(TyphoonData$`7級風暴風半徑(km)`) -> d
as.numeric(TyphoonData$`10級風暴風半徑(km)`) -> e
a
b
c
d
e
```


```{r}
z <- c(10485849600, 10477641600, 10561104000, 10562745600)
as.Date(as.POSIXct(z, origin = "1582-10-14", tz = "GMT"))

```


```{r}
cut(as.Date("2001/1/1") + 70*stats::runif(100), "")
```

```{r}
library(readr)
library(stringr)
library(lubridate)
TyphoonData <- read_csv("https://raw.githubusercontent.com/GaryLKL/course-programming-for-ds-Quiz/master/TyphoonData.csv", col_types = cols(.default = col_character()))
Year <- TyphoonData$年份
Year <- as.integer(Year)
Year <- Year - 1911
Year <- as.character(Year)
str_c("民國",Year,"年")
class("民國")


```

```{r}
y <- gl(2, 4, 8)
levels(y) <- c("low", "high")
y

```

```{r}
x <- c("Man", "Male", "Man", "Lady", "Female")
xf <- factor(x, levels = c("Male", "Man" , "Lady",   "Female"),
                 labels = c("Male", "Male", "Female", "Female"))
```

```{r}
z <- factor(LETTERS[3:1], ordered = TRUE)
stopifnot(sort(z)[c(1,3)] == range(z), min(z) < max(z))
```

```{r}

